- hosts: all
  become: true
  tasks:

  - name: install httpd
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"
  
  - name: install php support for httpd
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"