---

# Update all servers
- hosts: all
  become: true
  pre_tasks: 

  - name: update repo cache (Rocky)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB+9kWqu59KDJhrkZ0rH0JMamomcCn0rX1UncbbDcnS2 rocky-ansible-control"
    


# Install http/apache2 on [web_servers]
- hosts: web_servers
  become: true
  tasks:

  - name: install httpd and php for Rocky servers
    tags: apache, httpd, rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: start and enable httpd (Rocky)
    tags: rocky, http, apache
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"

  - name: change email address for admin
    tags: apache, rocky, httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Rocky"
    register: httpd

  - name: restart httpd (Rocky)
    tags: apache, rocky, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: install apache and php for Ubuntu servers
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


# Install mariadb on [db_servers]
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    tags: rocky, mariadb
    dnf: 
      name: 
        - mariadb
        - mariadb-server
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


# Install samba on [file_servers]
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
