---

# Update all servers
- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


# Install http/apache2 on [web_servers]
- hosts: web_servers
  become: true
  tasks:

  - name: install httpd and php for Rocky servers
    tags: apache, httpd, rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache and php for Ubuntu servers
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


# Install mariadb on [db_servers]
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    tags: rocky, mariadb
    dnf: 
      name: 
        - mariadb
        - mariadb-server
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


# Install samba on [file_servers]
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest